1 - Provide Path to your API Key

In [1]:
openai_key_path = '/Users/cu135/Library/CloudStorage/OneDrive-Personal/OneDrive_Documents/Work/Software/OpenAI/cu135_cbct_key.txt'

2 - Define your path to the CSV which contains the successfully screened titles
- This was printed at the end of the previous notebook.

In [2]:
title_review_path = "/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/ccm_memory/results/review_pyper/invasive/1962-2013_spreadsheet_cleaned.csv"

3 - Preprocess the Abstracts
- Provide the path to the location you saved the .txt file with the abstracts

In [3]:
# Define your path to the text file with the abstracts in it
abstracts_txt_path = '/Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/ccm_memory/results/review_pyper/invasive/1962-2013_abstracts.txt'

4 - Isolate the Abstracts which Passed Title Review

In [4]:
from calvin_utils.gpt_sys_review.txt_utils import AbstractSeparator
separator = AbstractSeparator(abstracts_txt_path)
df, abstracts_txt_path_preprocessed = separator.run()
df

                                               Abstract
0     1. Trends Neurosci. 1993 Jun;16(6):218-22. doi...
1     2. J Am Acad Child Adolesc Psychiatry. 1994 Ju...
2     3. N Engl J Med. 2012 May 17;366(20):1945; aut...
3     4. Handb Clin Neurol. 2013;116:681-91. doi: 10...
4     5. N Engl J Med. 2012 May 17;366(20):1945-6; a...
...                                                 ...
8845  8847. CNS Neurol Disord Drug Targets. 2010 Apr...
8846  8848. Int Immunol. 1998 Jul;10(7):901-10. doi:...
8847  8849. Psychiatr Genet. 2010 Jun;20(3):85-92. d...
8848  8850. Arch Gen Psychiatry. 2011 Jul;68(7):665-...
8849  8851. Endocr Rev. 2009 Aug;30(5):494-535. doi:...

[8850 rows x 1 columns]

In [5]:
from calvin_utils.gpt_sys_review.txt_utils import TitleReviewFilter
title_review_filter = TitleReviewFilter(title_review_path, abstracts_path=abstracts_txt_path_preprocessed, column_name="OpenAI_Screen")
df, abstracts_txt_path_preprocessed_filtered = title_review_filter.run()
df

                                               Abstract
1     2. J Am Acad Child Adolesc Psychiatry. 1994 Ju...
3     4. Handb Clin Neurol. 2013;116:681-91. doi: 10...
5     6. N Engl J Med. 2012 May 17;366(20):1945; aut...
6     7. Mol Neurobiol. 1997 Aug;15(1):17-29. doi: 1...
7     8. Cereb Cortex. 2007 Jan;17(1):108-15. doi: 1...
...                                                 ...
8809  8810. Neuropsychologia. 2007 Jan 28;45(2):282-...
8811  8812. Anesthesiology. 2001 Mar;94(3):390-9; di...
8820  8822. Behav Brain Funct. 2008 Feb 28;4:12. doi...
8821  8823. Brain Res. 2005 Jul 27;1051(1-2):81-9. d...
8834  8836. Eur J Immunol. 1998 May;28(5):1516-23. d...

[1464 rows x 1 columns]

5 - Evaluate Abstracts That Passed Title Screen
- Define your question, like in this example. Make it a question you WANT a yes to.     
      - question =  "Do you think this article may contain a case report of amnesia?"

In [6]:
question = "Does this article look like it may contain a report of invasive brain stimulation altering memory? Examples could include articles that talk about `brain stimulation`, `invasive EEG`, or `DBS`, and may discuss `memory enhancement`, `memory impairment`, or diseases like `alzheimers`."

In [7]:
from calvin_utils.gpt_sys_review.gpt_utils import AbstractScreener
abstract_screening = AbstractScreener(api_key_path=openai_key_path, csv_path=abstracts_txt_path_preprocessed_filtered, question=question, model_choice="gpt4", keywords=[])
screened_abstract_path = abstract_screening.run()

OpenAI Screening: 100%|██████████| 1464/1464 [15:42<00:00,  1.55it/s]

Saved finalized CSV to /Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/ccm_memory/results/review_pyper/invasive/1962-2013_abstracts_cleaned_filtered_cleaned.csv

6 - Postprocess Results

In [8]:
from calvin_utils.gpt_sys_review.txt_utils import PostProcessing
post_processor = PostProcessing(file1_path=abstracts_txt_path_preprocessed, file2_path=screened_abstract_path, pubmed_csv_path=title_review_path)
post_processor.run()

Found 228.0 abstracts
Saved Master List to:
 /Users/cu135/Partners HealthCare Dropbox/Calvin Howard/studies/ccm_memory/results/review_pyper/invasive/master_list.csv

,PMID,Title,Authors,Citation,First Author,Journal/Book,Publication Year,Create Date,PMCID,NIHMS ID,DOI,OpenAI_Screen,Abstract,OpenAI_Screen_Abstract
0,26983799,Fear Memory,"Izquierdo I, Furini CR, Myskiw JC.",Physiol Rev. 2016 Apr;96(2):695-750. doi: 10.1...,Izquierdo I,Physiol Rev,2016,2016/03/18,NaN,NaN,10.1152/physrev.00018.2015,0,1. Trends Neurosci. 1993 Jun;16(6):218-22. doi...,NaN
1,37857775,Non-invasive temporal interference electrical ...,"Violante IR, Alania K, Cassarà AM, Neufeld E, ...",Nat Neurosci. 2023 Nov;26(11):1994-2004. doi: ...,Violante IR,Nat Neurosci,2023,2023/10/19,PMC10620081,NaN,10.1038/s41593-023-01456-8,1,10. Behav Brain Res. 1997 Dec;89(1-2):1-34. do...,NaN
2,38388704,(R)-ketamine restores anterior insular cortex ...,"Yokoyama R, Ago Y, Igarashi H, Higuchi M, Tanu...",Mol Psychiatry. 2024 May;29(5):1406-1416. doi:...,Yokoyama R,Mol Psychiatry,2024,2024/02/22,PMC11189812,NaN,10.1038/s41380-024-02419-6,0,100. Trends Cogn Sci. 2006 Nov;10(11):487-93. ...,0.0
3,25170153,Targeted enhancement of cortical-hippocampal b...,"Wang JX, Rogers LM, Gross EZ, Ryals AJ, Dokucu...",Science. 2014 Aug 29;345(6200):1054-7. doi: 10...,Wang JX,Science,2014,2014/08/30,PMC4307924,NIHMS655169,10.1126/science.1252900,1,1000. Nature. 2011 Jan 27;469(7331):491-7. doi...,NaN
4,31753579,Disruption of Oligodendrogenesis Impairs Memor...,"Steadman PE, Xia F, Ahmed M, Mocle AJ, Penning...",Neuron. 2020 Jan 8;105(1):150-164.e6. doi: 10....,Steadman PE,Neuron,2020,2019/11/23,PMC7579726,NIHMS1636527,10.1016/j.neuron.2019.10.013,0,1001. Prog Brain Res. 2000;126:433-53. doi: 10...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9217,40141467,Premutation Females with preFXTAS,"Liani V, Torrents C, Rolleri E, Yusoff NA, Lik...",Int J Mol Sci. 2025 Mar 20;26(6):2825. doi: 10...,Liani V,Int J Mol Sci,2025,2025/03/27,PMC11942631,NaN,10.3390/ijms26062825,0,NaN,NaN
9218,38565579,Neuron-level explainable AI for Alzheimer's Di...,"Yousefzadeh N, Tran C, Ramirez-Zamora A, Chen ...",Sci Rep. 2024 Apr 2;14(1):7710. doi: 10.1038/s...,Yousefzadeh N,Sci Rep,2024,2024/04/02,PMC10987553,NaN,10.1038/s41598-024-58121-8,0,NaN,NaN
9219,38978575,Brain clocks capture diversity and disparity i...,"Moguilner S, Baez S, Hernandez H, Migeot J, Le...",Res Sq [Preprint]. 2024 Jun 25:rs.3.rs-4150225...,Moguilner S,Res Sq,2024,2024/07/09,PMC11230497,NaN,10.21203/rs.3.rs-4150225/v1,0,NaN,NaN
9220,39446224,"Complementary value of molecular, phenotypic, ...","Engvig A, Kalleberg KT, Westlye LT, Leonardsen...",Geroscience. 2025 Apr;47(2):2099-2118. doi: 10...,Engvig A,Geroscience,2025,2024/10/24,PMC11979055,NaN,10.1007/s11357-024-01376-w,0,NaN,NaN
9221,38383456,Deep phenotyping of post-infectious myalgic en...,"Walitt B, Singh K, LaMunion SR, Hallett M, Jac...",Nat Commun. 2024 Feb 21;15(1):907. doi: 10.103...,Walitt B,Nat Commun,2024,2024/02/21,PMC10881493,NaN,10.1038/s41467-024-45107-3,0,NaN,NaN

Your abstracts have now been screened. 
- If you are curious about screening titles then abstracts versus titles and abstracts, please see this study: 
    - doi: 10.2147/CLEP.S43118
- Enjoy. If this has been helpful, please consider adding Calvin Howard as a collaborator. 
- e: choward12@bwh.harvard.edu